import Vue from 'vue'
import VueRx from 'vue-rx'
import Rxjs from 'rxjs'
// import { Observable } from 'rxjs/Observable'
// import { Subscription } from 'rxjs/Subscription'
// import 'rxjs/add/observable/combineLatest'
// import 'rxjs/add/observable/from'
// import 'rxjs/add/observable/fromEvent'
// import 'rxjs/add/observable/fromPromise'
// import 'rxjs/add/observable/forkJoin'
// import 'rxjs/add/observable/of'
// import 'rxjs/add/observable/throw'
// import 'rxjs/add/operator/pluck'
// import 'rxjs/add/operator/distinctUntilChanged'
// import 'rxjs/add/operator/filter'
// import 'rxjs/add/operator/first'
// import 'rxjs/add/operator/last'
// import 'rxjs/add/operator/map'
// import 'rxjs/add/operator/do'
// import 'rxjs/add/operator/mergeMap'
// import 'rxjs/add/operator/toArray'
// import 'rxjs/add/operator/catch'
// import 'rxjs/add/operator/debounceTime'
// import 'rxjs/add/operator/finally'

Vue.use(VueRx, Rxjs)
